### PR TITLE
Sphinx based docs and rtd documentation

### PR DESCRIPTION
**Pull request by disko**
The documentation contains contents from the README broken up into multiple pages and an API docs section that is autogenerated from the sources' docstrings.  Some minor modifications have been made w.r.t. links beetween the doc pages.

The result is available here: https://confab.readthedocs.org/en/latest/.  Documentation is rebuilt on every push to the Github repository, currently set to my feature branch https://github.com/disko/confab/tree/feature/sphinx_and_rtd_documentation.  I'll happily switch to your master branch once the PR is merged and add you as a maintainer on the RTD project as soon as I know your RTD user name.

Hope you like it!

### CODE REVIEW

**Comment by jessemyers** [comment]
Thanks for the contribution. We're using git-flow for confab, so we aren't accepting pull requests against master. I should have time to merge this to develop manually fairly soon.

**Comment by jessemyers** [comment]
Quick follow up: it looks like a fair bit has changed between your fork and our develop branch, so this merge is going to be a bit more work than I expected originally.

**Comment by disko** [comment]
Oh, I didn't realize that you're using git flow.  I use it myself for all my projects but because of issues exactly like this I came to the conclusion that its default branch name suggestions are somewhat broken - at least for open source projects where not all contributors are aware of it.  That's why I name the development branch "master" and the production branch "production" nowadays.

However…  Instead of you merging my feature branch into develop, it might be easier if I tried to merge your "develop" branch into my feature branch, update the docs accordingly and then start a new pull request against the "develop" branch.  This likely won't happen before the weekend though.  What do you think?

**Comment by jessemyers** [comment]
That would be great; it would certainly save me a bit of time merging and would mean that your fork would have all of our latest changes. There's no hurry on our end. Obviously better docs are terrific, but they aren't blocking anything.

**Comment by disko** [comment]
Closing this PR.  Will re-open a new one against the develop branch.

**Pull request closed without merging**
